### ISSUE TITLE
Please consider "heatshrink"

### ISSUE THREAD

**Issue by markrages** [quixdb/squash-benchmark#1]
heatshrink is a compression library that is optimized for small embedded systems.  It has quite small memory footprint and CPU requirements.

I would be interested to see it compared to regular desktop compression algorithms.

Being designed for embedded use, it is portable.  And the source includes simple command-line compression and decompression tools.

https://github.com/atomicobject/heatshrink

**Comment by nemequ** [comment]
Adding libraries is an issue for squash, the benchmark just uses the squash plugins.

The bug for heatshrink is here: https://github.com/quixdb/squash/issues/52
