### ISSUE TITLE
Display the version or revision of libraries used

### ISSUE THREAD

**Issue by g1mv** [quixdb/squash-benchmark#15]
Sometimes there are noticeable differences between 2 different versions of the same library.
I don’t have a specific example but it’s easy to imagine that after a big update the numbers could turn out completely different (not saying in good or bad particularly, but as an example some type of files might benefit from an improvement and some might not).
That would make the accuracy of the benchmark results even better.

**Comment by nemequ** [comment]
I managed to get quixdb/squash#85 fixed, so it should be possible to take care of this now—I'll try to get it in to the next version (which is already overdue, but I wanted to take care of that issue first), as well as some other details like links to the upstream project and the plugin's squash documentation (e.g., https://quixdb.github.io/squash/api/c/md_plugins_density_density.html).

**Comment by nemequ** [comment]
Fixed in the web-next branch.
