### ISSUE TITLE
please update the brotli to the recent version

### ISSUE THREAD

**Issue by jyrkialakuijala** [quixdb/squash-benchmark#18]
there are a significant updates to the brotli repository since the last generated results

**Comment by nemequ** [comment]
The benchmark is still being run on some machines (phalanx and hoplite), but you can grab the development version from the new [squash-benchmark-web](https://github.com/quixdb/squash-benchmark-web) repository.  The new results will go live some time after the last two machines finish, probably Sunday or Monday.
