### ISSUE TITLE
feature request : single level benchmark

### ISSUE THREAD

**Issue by Cyan4973** [quixdb/squash-benchmark#25]
It's currently possible to select a compression algorithm to bench, using `-c algo`.
It works fine, but all defined compression levels are then tested by default.

It would be great if it was also possible to optionally select a single compression level, for finer tests.

For example, `-c algo,level` (idea from `fsbench`)

**Comment by nemequ** [comment]
Just added code so you can do `-c [plugin:]codec[/key=value[,key=value[,…]]]`.  You can also omit the key for an option it assumes it to be "level", so you can just do `-c lz4/3` as an alias for `-c lz4/level=3`.

**Comment by Cyan4973** [comment]
great option !
