### ISSUE TITLE
Speed result

### ISSUE THREAD

**Issue by Cyan4973** [quixdb/squash-benchmark#26]
minor feature request : get speed displayed for console results

when using current version of benchmark, results are provided using, I suspect, time in second. Some minor issues :
- Scale is not explicitly mentioned
- Number of significant digits can sometimes be too small, especially when the file benchmarked is very small and the algorithm selected is very fast

Example : 

```
./benchmark -c lz4 sum
Using sum:
  lz4:lz4
    level 1: compressed (0.0007 CPU, 0.0007 wall, 32004 bytes)... decompressed (0.000828 CPU, 0.000829 wall).
    level 2: compressed (0.0007 CPU, 0.0007 wall, 33343 bytes)... decompressed (0.001052 CPU, 0.001054 wall).
    level 3: compressed (0.0008 CPU, 0.0008 wall, 29358 bytes)... decompressed (0.000849 CPU, 0.000851 wall).
    level 4: compressed (0.0008 CPU, 0.0008 wall, 24915 bytes)... decompressed (0.000873 CPU, 0.000875 wall).
```

The number of significant digits is fine for decompression, but it's not for compression, as a slight difference in rounding can make > 10%.

Anyway, while I'm fine regarding this format (with possibly a bit more digits) for `-o jsonFile`, it's less agreeable to use for direct onscreen result.
One can always grab a calculator and manually type `size / time` to obtain speed, but it's less usable than having speed directly calculated on screen.

**Comment by nemequ** [comment]
Good point.  FWIW I think I did it this way to conserve horizontal real estate… at the time I was writing everything (incuding the dataset and codec) for every line, and I was trying to avoid wrapping.  Now that dataset and codec are on their own lines this isn't really an issue.

Anyways, fixed a few days ago, sorry I forgot to close then.
