### ISSUE TITLE
is this repo still uptodate with squash master?

### ISSUE THREAD

**Issue by psteinb** [quixdb/squash-benchmark#30]
Hi -

the Makefile yields squash-0.8 as the expected libsquash version
https://github.com/psteinb/squash-benchmark/blob/master/Makefile#L51

So I tried with master and the last release 0.7.0, but in both cases I get:

```
In file included from /home/steinbac/software/squash/0.7.0/include/squash-0.7/squash/squash.h:65:0,
                 from benchmark.c:38:
/home/steinbac/software/squash/0.7.0/include/squash-0.7/squash/options.h:121:27: note: expected ‘const char *’ but argument is of type ‘SquashCodec * {aka struct _SquashCodec *}’
 SQUASH_API int            squash_options_get_int       (SquashOptions* options, const char* key);
                           ^
benchmark.c:93:21: error: too many arguments to function ‘squash_options_get_int’
   const int level = squash_options_get_int (opts, codec, "level");
```

As `squash_options_get_int` is undocumented, I am unclear how to fix this.

**Comment by nemequ** [comment]
Master should work; I just tested here with a fresh install and there were no problems.  0.7, OTOH, will not work due to API changes.  The pasted error is from 0.7, can you paste the one from master?

`squash_options_get_int` [isn't undocumented](https://quixdb.github.io/squash/api/c/group__SquashOptions.html#gad18452932b71b89a1d60899fe3fcef6d), but the prototype has changed in git (see https://github.com/quixdb/squash/blob/master/squash/options.c#L235).

569759bf was the last commit targeting 0.7, so if you want you should be able to use that, too.

**Comment by psteinb** [comment]
mmmh, the error I pasted is from master with regard to squash/master

```
cc -Wall -Wextra -g -o benchmark benchmark.c timer.c `pkg-config --libs --cflags squash-0.8`
benchmark.c: In function ‘benchmark_codec_with_options’:
benchmark.c:93:51: warning: passing argument 2 of ‘squash_options_get_int’ from incompatible pointer type [-Wincompatible-pointer-types]
   const int level = squash_options_get_int (opts, codec, "level");
                                                   ^
In file included from /home/steinbac/software/squash/master/include/squash-0.8/squash/squash.h:141:0,
                 from benchmark.c:38:
/home/steinbac/software/squash/master/include/squash-0.8/squash/options.h:132:27: note: expected ‘const char *’ but argument is of type ‘SquashCodec * {aka struct SquashCodec_ *}’
 SQUASH_API int            squash_options_get_int       (SquashOptions* options, const char* key);
                           ^
benchmark.c:93:21: error: too many arguments to function ‘squash_options_get_int’
   const int level = squash_options_get_int (opts, codec, "level");
```

and to make sure, I double checked the pkg-config output:

```
$ pkg-config --libs --cflags squash-0.8
-I/home/steinbac/software/squash/master/include/squash-0.8 -L/home/steinbac/software/squash/master/lib -lsquash0.8
```

**Comment by nemequ** [comment]
It looks like the header you have installed includes the old signature for `squash_options_get_int`.  Could the header be from an old version of master (before the function was changed)?

**Comment by psteinb** [comment]
a fresh install under temp reveals the expected behavior. So it must 
have been my mistake somewhere. Sorry for the noise!
