### ISSUE TITLE
Disagreement on hyphen in squash library name

### ISSUE THREAD

**Issue by travisdowns** [quixdb/squash-benchmark#34]
With a locally built and installed version of libsquash 0.8, the benchmark doesn't build due to a disagreement about whether the library name is `libsquash-0.8` or `libsquash0.8`.

The benchmark `Makefile` uses `pkg-config --libs --cflags squash-0.8` to link libsquash, which returns:

    -I/usr/local/include -I/usr/local/include/squash-0.8 -L/usr/local/lib -lsquash-0.8

However, the actual libraries installed into `/usr/local/lib` don't have the hyphen:

```
lrwxrwxrwx 1 root root       21 Jan  4 17:11 libsquash0.8.so -> libsquash0.8.so.0.8.0
-rw-r--r-- 1 root root   383072 Jan  3 18:01 libsquash0.8.so.0.8
lrwxrwxrwx 1 root root       19 Jan  4 17:11 libsquash0.8.so.0.8.0 -> libsquash0.8.so.0.8
```

So the benchmark build fails with:

```
cc -Wall -Wextra -g -o benchmark benchmark.c timer.c `pkg-config --libs --cflags squash-0.8`
/usr/bin/ld: cannot find -lsquash-0.8
```

**Comment by travisdowns** [comment]
As a workaround, you can add a symlink for the hyphenated version and then the build is happy:

    sudo ln -s /usr/local/lib/libsquash0.8.so /usr/local/lib/libsquash-0.8.so

**Comment by nemequ** [comment]
Fixed the pkg-config file in Squash.  It looks like I screwed some other stuff up regarding the installed header location, too…  Should be fixed now.

I'll add a test to squash to make sure this doesn't happen again.  Sorry :(

**Comment by travisdowns** [comment]
I confirmed this works, without the symlink, after pulling down your changes.

**Comment by nemequ** [comment]
Excellent, thanks.  Sorry about the SNAFU :(.

I did add that test to Squash, so this shouldn't happen again.
