### ISSUE TITLE
Add a transmission graph

### ISSUE THREAD

**Issue by nemequ** [quixdb/squash-benchmark#4]
(Originally posted to https://github.com/quixdb/squash/issues/82 by @gpnuma):

Here's an issue to make things easy to track for you :)
A transmission speed graph would be very informative, in addition to the other graphs which are very valuable already.
Same principle as this : http://fastcompression.blogspot.fr/p/compression-benchmark.html.

Also, a round trip speed graph in x / ratio in y (a derivative of the previous but with unlimited transmission speed) would also be interesting as a standalone as it gives the general qualities of each algorithm depending on files and platforms.
I think comparing only compression speed/ratio on one side and on the other side decompression speed/ratio is a bit limited, because you could easily create an algorithm that compresses very slowly and decompresses ultra quickly, as well as - although probably harder - an algorithm that compresses extremely quickly and decompresses very slowly if you see what I mean.
Whereas having assets in both areas (like all well-known algorithms) is much more difficult hence the idea of this round trip graph.
Thanks !

**Comment by nemequ** [comment]
At first glance I thought this might be doable, but unless I'm missing something there would have to be 178 lines which is, I think, way too much information to process.

**Comment by g1mv** [comment]
Thanks for moving the issue I had no idea you also had a repository for the benchmark itself.
You're right it might be a very crowded graph indeed ... way too much information to plot.
However the second idea (round trip speed in x / ratio in y) is doable because the resulting output is a point, and 178 points can fit as we can see in your other graphs.

**Comment by nemequ** [comment]
I definitely like the round trip time idea… I'm just wondering if the value should be `compress_cpu + decompress_cpu`, or `(compress_cpu + decompress_cpu) / uncompressed_size`.  The second feels a bit more contrived, but it makes it possible to compare values across datasets.

**Comment by g1mv** [comment]
I was rather thinking of speed in MB/s relative to the original uncompressed file in x, and ratio as a multiplier (like 2.0x if the resulting file is 50% smaller than uncompressed version) in y.
That way dataset size doesn't matter.
For example, if you have a codec compressing and decompressing at 100MB/s, with a fixed 2.0 ratio and a 100MB dataset, in x you would plot 100 MB / (1s + 1s) = 50MB/s and on y you would plot 2.0 (it takes 1s to compress 100MB to 50MB and another second to decompress 50MB back to 100MB).
Or even better you could plot 100MB in x as the codec has actually "processed" 200MB in 2s.
What do you think ?

**Comment by nemequ** [comment]
Done, thanks.

**Comment by g1mv** [comment]
This is great !! Very interesting.
I think there's a small glitch in the x axis scale, it seems like it's half of what it should be apparently.
Thanks

**Comment by nemequ** [comment]
That's… puzzling…

**Comment by nemequ** [comment]
Ah, no, it's right.  It's `uncompressed_size / (compress_cpu + decompress_cpu)`.  You're probably thinking it would just be `compression_rate + decompression_rate` (that was my first thought when I saw your comment).

**Comment by g1mv** [comment]
In that case maybe the scale should output (2 \* uncompressed_size) / (compress_cpu + decompress_cpu) ?
Nothing important but it's weird to see compress speed 200MB/s, decompress speed 200MB/s when you click on a dot, and then see a 100MB/s scale indicator underneath.

...Actually now I get it, never mind, you represent the total round trip speed as the title says :)
Nice work !

**Comment by nemequ** [comment]
Hm, I suppose that makes sense—you are processing the data twice.
