### ISSUE TITLE
Create memcpy plugin

### ISSUE THREAD

**Issue by nemequ** [quixdb/squash-benchmark#5]
Should help provide a baseline.

**Comment by quackenbush** [comment]
I should have opened the memcpy issue for you over here.  Thanks.

**Comment by nemequ** [comment]
I was going to put this in the benchmark instead of squash (hence opening a bug here instead of there), but it could be useful to disable compression at times without having to write an extra code path, so I added the plugin to Squash instead.

**Comment by nemequ** [comment]
(Note that it will not show up in the benchmark until I run it again, so probably not until next week.)
