### ISSUE TITLE
json and msgpack datasets

### ISSUE THREAD

**Issue by abotsis** [quixdb/squash-benchmark#7]
json and msgpack are fairly trendy these days. seeing results for these would be great! It'd be even better if all serialization formats (protobuf, xml, json, msgpack) all originated from the same dataset.

**Comment by nemequ** [comment]
Thanks, I think we can use #6 for this, I'll post a message there when the new project is born.  I wasn't planning on msgpack, but I do plan on JSON and protobuf…  I'll take a look msgpack—it seems a lot like Thrift or BSON, so maybe it would make sense to add at least one of them.
