### ISSUE TITLE
floating point data

### ISSUE THREAD

**Issue by IorPerry** [quixdb/squash-benchmark#9]
Hello, 
I am a 3D programmer, and should be great check for a list of 32bit floating point data, maybe a stanford 3D scanned model: http://graphics.stanford.edu/data/3Dscanrep/
Best regards,
Perry

**Comment by nemequ** [comment]
I'm working on [a new corpus](https://github.com/nemequ/squash-corpus) which will be added to the benchmark.  We should discuss this there.
